project:
  type: website

website:
  title: Exploring income and physical activity disparities in the US
  navbar:
    right:
      - icon: github
        href: https://github.com/INFO-511-F24/final-project-TheOutliers # Needs to be changed to your project repo
    left:
      - text: Project
        href: index.qmd
      - text: Proposal
        href: proposal.qmd
      - text: Presentation
        href: presentation.qmd
      - text: About
        href: about.qmd

format:
  html:
    theme:
      light: flatly
      dark: darkly
    toc: true


execute:
  freeze: auto
