{
  "hash": "a4388d90dddbafd6e3f0835e1baaafa7",
  "result": {
    "engine": "jupyter",
    "markdown": "---\ntitle: \"Data, Data, Data\"\nsubtitle: \"Oh My\"\nauthor:\n  - name: \"The Outliers\"\n    affiliations:\n      - name: \"School of Information, University of Arizona\"\ndescription: \"Final Project: Milestone 2\"\nformat:\n  html:\n    code-tools: true\n    code-overflow: wrap\n    code-line-numbers: true\n    embed-resources: true\neditor: visual\ncode-annotations: hover\nexecute:\n  warning: false\njupyter: python3\n---\n\n::: {#load-pkgs .cell message='false' execution_count=1}\n``` {.python .cell-code}\nimport numpy as np\nimport seaborn as sns\nimport pandas as pd\n```\n:::\n\n\n## Introduction and data\n\n\nFor each data set:\n\n-   Identify the source of the data.\n\n-   State when and how it was originally collected (by the original data curator, not necessarily how you found the data).\n\n-   Write a brief description of the observations.\n\n-   Address ethical concerns about the data, if any.\n\nMake sure to load the data and use inline code for some of this information.\n\n## Research Question\n\nYour research question should contain at least three variables, and should be a mix of categorical and quantitative variables. When writing a research question, please think about the following:\n\n-   What is your target population?\n\n-   Is the question original?\n\n-   Can the question be answered?\n\nFor each data set, include the following:\n\n-   A well formulated research question. (You may include more than one research question if you want to receive feedback on different ideas for your project. However, one per data set is required.)\n\n-   Statement on why this question is important.\n\n-   A description of the research topic along with a concise statement of your hypotheses on this topic.\n\n-   Identify the types of variables in your research question. Categorical? Quantitative?\n\n## Glimpse of data\n\nFor each data set:\n\n-   Place the file containing your data in the data folder of the project repo.\n\n-   Use the `.head()` and `.info()` functions to provide a glimpse of the data set.\n\n## Analysis plan\n\n-   A plan for answering each of the questions including the variables involved, variables to be created (if any), external data to be merged in (if any).\n\n## Dataset 1: Nutrition, physical activity, and obesity\n\n### Introduction and data\n\nThis dataset was provided by the Centers for Disease Control and Provention (CDC), National Center for Chronic Disease prevention and Health Promotion, Division of Nutrition, Physical Activity, and Obesity. This data was collected through health-related telephone surveys that gather state data about U.S. Residents. This dataset has been used for the Data, Trends, and Maps database that the Division of Nutrition, Physical Activity, and Obesity (DNPAO) section of the CDC has, which is responsible for providing both state and national data for these topics.\n\n#### Description of contents\n\nThis dataset includes over 104 thousand rows, and has 33 columns. Each row represents a combination of a year, state, survey question, and percent of individuals who are positively identified for that question, along with stratification. The categories for stratification are Age Range, Education, Gender, Income, Race/Ethnicity, and Total.\n\nSurvey questions fall into the categories of \"Fruits and Vegetables - Behavior\", \"Obesity/Weight Status\", and \"Physical Activity - Behavior\". Examples of survey questions include \"Percent of adults who engage in muscle-strengthening activities on 2 or more days a week\" and \"Percent of adults aged 18 years and older who have obesity\".\n\nThis dataset includes observations for the years 2011-2023. Percentages and data are not included for groups with insufficient sample sizes.\n\n#### Ethical Concerns\n\nThere are no particular ethical concerns regarding working with this data. This dataset is aggregated, and numbers are excluded in instances where the sample size is too small. This removes concerns surrounding the personal identification of individuals within this dataset. This dataset is publicly available for anyone to download, and the licensing agreement states that it is free to be shared, created, and adapted, as long as it is attributed as the data source when publicly displayed or published. This removes concerns surrounding unfair or illegal acquisition and use of the data.\n\n### Research Question\n\n-   Research Question: Do higher-income populations consistently have more time for physical activity than lower income populations?\n\n    -   Additional research questions include: How has the relationship between amount of physical activity and income changed over time? How does this vary between groups? And how does the amount of physical activity that lower-income populations have the time to do changed over the years?\n\n    -   The target population for this research question is U.S. Residents 18 and over, represented by the dataset\n\n-   This question is important because it may highlight areas that correlate with differences in physical health across the population. If there are groupings that are identified that are tied to physical health and activity more than others, then more research can be done to identify ways in which these groups can receive more assistance with nutrition and adopting healthier lifestyles. \n\n-   The research topic of interest here is whether or not there is a relationship between the amount of income that an individual makes and the amount of physical activity they are able to make time for. This falls in a larger category of interest surrounding differences between physical activity and nutrition for different groups and subsets of the population.\n\n-   We hypothesize that individuals who have lower income levels will have less time for physical activity, showing that larger percentages of the low income population will fall into the “Percent of adults who engage in no leisure-time physical activity” group compared to individuals with higher incomes. \n\n-   The variables in this research question are mostly categorical, the questions themselves and the groupings (income range) are both categorical. The percentage of respondents who fall into each category is a quantitative variable, and there is a time element (years) which can be used as well.\n\n### Glimpse of data\n\n::: {#450ad760 .cell execution_count=3}\n``` {.python .cell-code}\nnutrition = pd.read_csv(\"data/nutrition.csv\")\n```\n:::\n\n\n::: {#05d7deb5 .cell execution_count=4}\n``` {.python .cell-code}\nnutrition.head()\n```\n\n::: {.cell-output .cell-output-display execution_count=3}\n```{=html}\n<div>\n<style scoped>\n    .dataframe tbody tr th:only-of-type {\n        vertical-align: middle;\n    }\n\n    .dataframe tbody tr th {\n        vertical-align: top;\n    }\n\n    .dataframe thead th {\n        text-align: right;\n    }\n</style>\n<table border=\"1\" class=\"dataframe\">\n  <thead>\n    <tr style=\"text-align: right;\">\n      <th></th>\n      <th>YearStart</th>\n      <th>YearEnd</th>\n      <th>LocationAbbr</th>\n      <th>LocationDesc</th>\n      <th>Datasource</th>\n      <th>Class</th>\n      <th>Topic</th>\n      <th>Question</th>\n      <th>Data_Value_Unit</th>\n      <th>Data_Value_Type</th>\n      <th>...</th>\n      <th>GeoLocation</th>\n      <th>ClassID</th>\n      <th>TopicID</th>\n      <th>QuestionID</th>\n      <th>DataValueTypeID</th>\n      <th>LocationID</th>\n      <th>StratificationCategory1</th>\n      <th>Stratification1</th>\n      <th>StratificationCategoryId1</th>\n      <th>StratificationID1</th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>0</th>\n      <td>2011</td>\n      <td>2011</td>\n      <td>AK</td>\n      <td>Alaska</td>\n      <td>BRFSS</td>\n      <td>Obesity / Weight Status</td>\n      <td>Obesity / Weight Status</td>\n      <td>Percent of adults aged 18 years and older who ...</td>\n      <td>2011.0</td>\n      <td>Value</td>\n      <td>...</td>\n      <td>(64.845079957001, -147.722059036)</td>\n      <td>OWS</td>\n      <td>OWS1</td>\n      <td>Q036</td>\n      <td>VALUE</td>\n      <td>2</td>\n      <td>Race/Ethnicity</td>\n      <td>2 or more races</td>\n      <td>RACE</td>\n      <td>RACE2PLUS</td>\n    </tr>\n    <tr>\n      <th>1</th>\n      <td>2011</td>\n      <td>2011</td>\n      <td>AK</td>\n      <td>Alaska</td>\n      <td>BRFSS</td>\n      <td>Obesity / Weight Status</td>\n      <td>Obesity / Weight Status</td>\n      <td>Percent of adults aged 18 years and older who ...</td>\n      <td>2011.0</td>\n      <td>Value</td>\n      <td>...</td>\n      <td>(64.845079957001, -147.722059036)</td>\n      <td>OWS</td>\n      <td>OWS1</td>\n      <td>Q036</td>\n      <td>VALUE</td>\n      <td>2</td>\n      <td>Race/Ethnicity</td>\n      <td>Other</td>\n      <td>RACE</td>\n      <td>RACEOTH</td>\n    </tr>\n    <tr>\n      <th>2</th>\n      <td>2011</td>\n      <td>2011</td>\n      <td>AK</td>\n      <td>Alaska</td>\n      <td>BRFSS</td>\n      <td>Physical Activity</td>\n      <td>Physical Activity - Behavior</td>\n      <td>Percent of adults who achieve at least 150 min...</td>\n      <td>2011.0</td>\n      <td>Value</td>\n      <td>...</td>\n      <td>(64.845079957001, -147.722059036)</td>\n      <td>PA</td>\n      <td>PA1</td>\n      <td>Q044</td>\n      <td>VALUE</td>\n      <td>2</td>\n      <td>Gender</td>\n      <td>Female</td>\n      <td>GEN</td>\n      <td>FEMALE</td>\n    </tr>\n    <tr>\n      <th>3</th>\n      <td>2011</td>\n      <td>2011</td>\n      <td>AK</td>\n      <td>Alaska</td>\n      <td>BRFSS</td>\n      <td>Obesity / Weight Status</td>\n      <td>Obesity / Weight Status</td>\n      <td>Percent of adults aged 18 years and older who ...</td>\n      <td>2011.0</td>\n      <td>Value</td>\n      <td>...</td>\n      <td>(64.845079957001, -147.722059036)</td>\n      <td>OWS</td>\n      <td>OWS1</td>\n      <td>Q036</td>\n      <td>VALUE</td>\n      <td>2</td>\n      <td>Age (years)</td>\n      <td>35 - 44</td>\n      <td>AGEYR</td>\n      <td>AGEYR3544</td>\n    </tr>\n    <tr>\n      <th>4</th>\n      <td>2011</td>\n      <td>2011</td>\n      <td>AK</td>\n      <td>Alaska</td>\n      <td>BRFSS</td>\n      <td>Obesity / Weight Status</td>\n      <td>Obesity / Weight Status</td>\n      <td>Percent of adults aged 18 years and older who ...</td>\n      <td>2011.0</td>\n      <td>Value</td>\n      <td>...</td>\n      <td>(64.845079957001, -147.722059036)</td>\n      <td>OWS</td>\n      <td>OWS1</td>\n      <td>Q037</td>\n      <td>VALUE</td>\n      <td>2</td>\n      <td>Income</td>\n      <td>$15,000 - $24,999</td>\n      <td>INC</td>\n      <td>INC1525</td>\n    </tr>\n  </tbody>\n</table>\n<p>5 rows × 33 columns</p>\n</div>\n```\n:::\n:::\n\n\n::: {#c068ef10 .cell execution_count=5}\n``` {.python .cell-code}\nnutrition.info()\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n<class 'pandas.core.frame.DataFrame'>\nRangeIndex: 104272 entries, 0 to 104271\nData columns (total 33 columns):\n #   Column                      Non-Null Count   Dtype  \n---  ------                      --------------   -----  \n 0   YearStart                   104272 non-null  int64  \n 1   YearEnd                     104272 non-null  int64  \n 2   LocationAbbr                104272 non-null  object \n 3   LocationDesc                104272 non-null  object \n 4   Datasource                  104272 non-null  object \n 5   Class                       104272 non-null  object \n 6   Topic                       104272 non-null  object \n 7   Question                    104272 non-null  object \n 8   Data_Value_Unit             88872 non-null   float64\n 9   Data_Value_Type             104272 non-null  object \n 10  Data_Value                  93505 non-null   float64\n 11  Data_Value_Alt              93505 non-null   float64\n 12  Data_Value_Footnote_Symbol  10767 non-null   object \n 13  Data_Value_Footnote         10767 non-null   object \n 14  Low_Confidence_Limit        93505 non-null   float64\n 15  High_Confidence_Limit       93505 non-null   float64\n 16  Sample_Size                 93505 non-null   float64\n 17  Total                       3724 non-null    object \n 18  Age(years)                  22344 non-null   object \n 19  Education                   14896 non-null   object \n 20  Gender                      7448 non-null    object \n 21  Income                      26068 non-null   object \n 22  Race/Ethnicity              29792 non-null   object \n 23  GeoLocation                 102340 non-null  object \n 24  ClassID                     104272 non-null  object \n 25  TopicID                     104272 non-null  object \n 26  QuestionID                  104272 non-null  object \n 27  DataValueTypeID             104272 non-null  object \n 28  LocationID                  104272 non-null  int64  \n 29  StratificationCategory1     104272 non-null  object \n 30  Stratification1             104272 non-null  object \n 31  StratificationCategoryId1   104272 non-null  object \n 32  StratificationID1           104272 non-null  object \ndtypes: float64(6), int64(3), object(24)\nmemory usage: 26.3+ MB\n```\n:::\n:::\n\n\n### Analysis plan\n\nInitial detailed exploration of the data (focusing on the main variables involved) will be followed by data cleaning and some wrangling. Identification of missing observations, data type conversions, etc. will be addressed in these initial steps. The variables involved to answer the largest research question include the \"Question\" and \"Income\" and \"StratificationCategoryId1\" columns, as well as the \"Data_Value\" column and the \"YearStart\" column. New columns that group some of these variables may also be created, such as grouping the \"Income\" values into \"Low Income\" and \"High Income\". At this point there is no plan to bring in and merge any external data.\n\nOnce the data has been wrangled, it can be visualized in an assortment of plots for analysis, and summary statistics by group can be compiled as well. These visualizations and statistics will allow for insight as to how the relationship between income and physical activity compares between groups, as well as over time. From here, additional metrics can be run, plots created, etc. to explore and dive in further.\n\n## Dataset 2: Private sector AI activity indicators\n\n### Introduction and data\n\nThe dataset was constructed by the Emerging Technology Observatory (ETO), a project of the Center for Security and Emerging Technology at Georgetown University. The information about company stages of development and company metadata was generated using data from Crunchbase, a tool for business insights. Publications data was obtained from another project by the ETO, their Merged Academic Corpus, which contains information about scholarly articles. Machine learning models were used to identify AI related publications. Patent information was obtained from 1790 Analytics, PATSTAT, and The Lens. Workforce related data was compiled and processed from LinkedIn profiles by Revelio Labs.\n\n#### Description of contents\n\nThe dataset contains indicators of business and R&D activity related to AI for many private sector companies. The dataset contains 5 tables, core, ticker, alias, id, and yearly_publication_counts. We chose to focus on the core table for the purposes of this project.\n\nThe core table includes metadata and metrics related to publication, patent, and worker data regarding AI. The metadata includes a company name, unique numeric id, region of the world, stage of development, business sector, and description of the company, among other information.\n\nThe table also contains counts of AI research publications, average percent increase in publications per year over the past 3 years, percent of total publications that were related to AI, and metrics related to citations and presence in conferences. The counts of publications are also divided into the categories of computer vision, NLP, and robotics.\n\nThe patent information is separated into total patents, average percent increase in patents per year over the past 3 years, percentage of total patents related to AI, and granted patents. The patents are separated into subcategories. There are 2 main subcategories, ‘AI use cases’ and ‘AI applications and techniques’, which are further divided into more subcategories. These include energy, transportation, security for ‘AI use cases’, and computer vision, language processing, and distributed AI for ‘AI applications and techniques’.\n\nThe workforce data consists of 2 columns containing the number of AI workers and ‘Tech Team 1’ workers. Tech Team 1 is defined as “anyone with technical skills and a reasonable probability of working with AI” and is derived from Revelio Labs’ taxonomy of highly technical roles and their responsibilities. More information on this definition can be found in the dataset’s documentation. The AI workers metric is defined as a subset of Tech Team 1 with a high probability of working with AI.\n\n#### Ethics of working with this dataset\n\nThe data was acquired from secondary sources (Crunchbase, PATSTAT, LinkedIn) so users of this dataset must be aware of the limitations of each individual source to make informed ethical decisions when making inferences using it. This could include ethical concerns regarding the use of LinkedIn users' data, when these users did not explicitly consent to it being used for this purpose, although they did agree with the site's terms of service.\n\nThe dataset authors address some limitations of the dataset in the description and there may be some ethical concerns related to making broad generalizations based on this dataset, which does not represent the entire population of all companies working with AI. One concern is that the workforce metrics are incomplete because they are based on LinkedIn data. As a result, the dataset could be biased towards United States residents and against other regions of the world, as LinkedIn is less popular in other countries and is blocked in some countries like Russia and China.\n\nAnother ethical concern could be that the dataset is heavily focused on large and established companies, and neglects other areas of AI development such as small companies, non-patented innovation, and open source projects. The dataset is also heavily reliant on publicly available and self reported data, which could make less public companies underrepresented such as companies who are doing work related to sensitive topics or are focused on proprietary innovations.\n\nThere may also be bias in the model used to identify AI-related publications, which could lead to an incomplete or misleading representation of actual AI research activity.\n\n### Research Question\n\n-   What relationships are there between the **number of AI publications** and **patents** and the **sector** of the companies represented in this dataset? \n\n    -   Target population: Companies represented in dataset\n\n-   This question is important because AI is a rapidly growing field of research and investment. Understanding the sectors in which the most innovation is occurring can help guide business decisions of companies and investors. For example, investors who are interested in new technologies may want to invest in companies with higher numbers of AI publications and patents, while investors who have ethical concerns regarding the use of AI may be interested in fields with less development in this area. \n\n-   The topic of research is private-sector AI research activity, specifically related to the number of patents and research publications.\n\n-   We hypothesize that the sectors ‘Software and IT Services”, ‘Banking and Investment Services’, and ‘Financial Technology (Fintech) & Infrastructure’ will have high numbers of AI related publications and patents, while ‘Food & Beverages’, ‘Food & Drug Retailing’, and ‘Personal & Household Products & Services’ will have lower levels of publications and patents.\n\n-   Most of the variables are numeric and quantitative as they represent numerical quantities describing levels of AI related business activity, such as the variables in the subcategories Publications, Patents, and Workforce. The categorical qualitative variables include Name, Country, Region, and Sector. \n\n### Glimpse of data\n\n::: {#d0cad752 .cell execution_count=6}\n``` {.python .cell-code}\nai = pd.read_csv(\"data/private_sector_ai_indicators.csv\")\n```\n:::\n\n\n::: {#88b0fcd4 .cell execution_count=7}\n``` {.python .cell-code}\nai.head()\n```\n\n::: {.cell-output .cell-output-display execution_count=6}\n```{=html}\n<div>\n<style scoped>\n    .dataframe tbody tr th:only-of-type {\n        vertical-align: middle;\n    }\n\n    .dataframe tbody tr th {\n        vertical-align: top;\n    }\n\n    .dataframe thead th {\n        text-align: right;\n    }\n</style>\n<table border=\"1\" class=\"dataframe\">\n  <thead>\n    <tr style=\"text-align: right;\">\n      <th></th>\n      <th>Name</th>\n      <th>ID</th>\n      <th>Country</th>\n      <th>Website</th>\n      <th>Groups</th>\n      <th>Aggregated subsidiaries</th>\n      <th>Region</th>\n      <th>Stage</th>\n      <th>Sector</th>\n      <th>Description</th>\n      <th>...</th>\n      <th>Patents: AI applications and techniques: Language processing</th>\n      <th>Patents: AI applications and techniques: Measuring and testing</th>\n      <th>Patents: AI applications and techniques: Planning and scheduling</th>\n      <th>Patents: AI applications and techniques: Robotics</th>\n      <th>Patents: AI applications and techniques: Speech processing</th>\n      <th>Workforce: AI workers</th>\n      <th>Workforce: Tech Team 1 workers</th>\n      <th>City</th>\n      <th>State/province</th>\n      <th>PARAT link</th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>0</th>\n      <td>Accenture</td>\n      <td>803</td>\n      <td>Ireland</td>\n      <td>https://www.accenture.com/</td>\n      <td>S&amp;P 500</td>\n      <td>NaN</td>\n      <td>Europe</td>\n      <td>Mature</td>\n      <td>Software &amp; IT Services</td>\n      <td>Accenture is a professional services company, ...</td>\n      <td>...</td>\n      <td>33</td>\n      <td>13</td>\n      <td>129</td>\n      <td>0</td>\n      <td>23</td>\n      <td>13610</td>\n      <td>166212</td>\n      <td>Dublin</td>\n      <td>Dublin</td>\n      <td>https://parat.eto.tech/company/803-accenture</td>\n    </tr>\n    <tr>\n      <th>1</th>\n      <td>Cognizant</td>\n      <td>806</td>\n      <td>United States</td>\n      <td>https://www.cognizant.com</td>\n      <td>S&amp;P 500</td>\n      <td>NaN</td>\n      <td>North America</td>\n      <td>Mature</td>\n      <td>Software &amp; IT Services</td>\n      <td>Cognizant is a professional services company, ...</td>\n      <td>...</td>\n      <td>1</td>\n      <td>0</td>\n      <td>7</td>\n      <td>0</td>\n      <td>5</td>\n      <td>5226</td>\n      <td>130530</td>\n      <td>Teaneck</td>\n      <td>New Jersey</td>\n      <td>https://parat.eto.tech/company/806-cognizant</td>\n    </tr>\n    <tr>\n      <th>2</th>\n      <td>Amazon</td>\n      <td>23</td>\n      <td>United States</td>\n      <td>http://amazon.com</td>\n      <td>S&amp;P 500, Global Big Tech</td>\n      <td>Amazon Advertising, Amazon Web Services</td>\n      <td>North America</td>\n      <td>Mature</td>\n      <td>Retailers</td>\n      <td>Amazon is a global tech firm with a focus on e...</td>\n      <td>...</td>\n      <td>23</td>\n      <td>179</td>\n      <td>131</td>\n      <td>9</td>\n      <td>265</td>\n      <td>14164</td>\n      <td>128587</td>\n      <td>Seattle</td>\n      <td>Washington</td>\n      <td>https://parat.eto.tech/company/23-amazon</td>\n    </tr>\n    <tr>\n      <th>3</th>\n      <td>IBM</td>\n      <td>115</td>\n      <td>United States</td>\n      <td>http://www.ibm.com/</td>\n      <td>S&amp;P 500, Global Big Tech</td>\n      <td>NaN</td>\n      <td>North America</td>\n      <td>Mature</td>\n      <td>Software &amp; IT Services</td>\n      <td>IBM is an IT technology and consulting firm pr...</td>\n      <td>...</td>\n      <td>386</td>\n      <td>296</td>\n      <td>828</td>\n      <td>4</td>\n      <td>471</td>\n      <td>6113</td>\n      <td>117515</td>\n      <td>Armonk</td>\n      <td>New York</td>\n      <td>https://parat.eto.tech/company/115-ibm</td>\n    </tr>\n    <tr>\n      <th>4</th>\n      <td>Microsoft</td>\n      <td>163</td>\n      <td>United States</td>\n      <td>http://www.microsoft.com</td>\n      <td>S&amp;P 500, Global Big Tech, GenAI Contenders</td>\n      <td>NaN</td>\n      <td>North America</td>\n      <td>Mature</td>\n      <td>Software &amp; IT Services</td>\n      <td>Microsoft is a software corporation that devel...</td>\n      <td>...</td>\n      <td>214</td>\n      <td>61</td>\n      <td>550</td>\n      <td>0</td>\n      <td>365</td>\n      <td>5245</td>\n      <td>104414</td>\n      <td>Redmond</td>\n      <td>Washington</td>\n      <td>https://parat.eto.tech/company/163-microsoft</td>\n    </tr>\n  </tbody>\n</table>\n<p>5 rows × 61 columns</p>\n</div>\n```\n:::\n:::\n\n\n::: {#82142642 .cell execution_count=8}\n``` {.python .cell-code}\nai.info()\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n<class 'pandas.core.frame.DataFrame'>\nRangeIndex: 691 entries, 0 to 690\nData columns (total 61 columns):\n #   Column                                                             Non-Null Count  Dtype  \n---  ------                                                             --------------  -----  \n 0   Name                                                               691 non-null    object \n 1   ID                                                                 691 non-null    int64  \n 2   Country                                                            690 non-null    object \n 3   Website                                                            690 non-null    object \n 4   Groups                                                             529 non-null    object \n 5   Aggregated subsidiaries                                            15 non-null     object \n 6   Region                                                             690 non-null    object \n 7   Stage                                                              691 non-null    object \n 8   Sector                                                             691 non-null    object \n 9   Description                                                        686 non-null    object \n 10  Description source                                                 686 non-null    object \n 11  Description link                                                   686 non-null    object \n 12  Description date                                                   686 non-null    object \n 13  Publications: AI publications                                      691 non-null    int64  \n 14  Publications: Recent AI publication growth                         336 non-null    float64\n 15  Publications: AI publication percentage                            691 non-null    float64\n 16  Publications: AI publications in top conferences                   691 non-null    int64  \n 17  Publications: Citations to AI research                             691 non-null    int64  \n 18  Publications: CV publications                                      691 non-null    int64  \n 19  Publications: NLP publications                                     691 non-null    int64  \n 20  Publications: Robotics publications                                691 non-null    int64  \n 21  Publications: Total publications                                   691 non-null    int64  \n 22  Patents: AI patents                                                691 non-null    int64  \n 23  Patents: AI patents: recent growth                                 331 non-null    float64\n 24  Patents: AI patent percentage                                      691 non-null    float64\n 25  Patents: Granted AI patents                                        691 non-null    int64  \n 26  Patents: Total patents                                             691 non-null    int64  \n 27  Patents: AI use cases: Agriculture                                 691 non-null    int64  \n 28  Patents: AI use cases: Banking and finance                         691 non-null    int64  \n 29  Patents: AI use cases: Business                                    691 non-null    int64  \n 30  Patents: AI use cases: Computing in government                     691 non-null    int64  \n 31  Patents: AI use cases: Document management and publishing          691 non-null    int64  \n 32  Patents: AI use cases: Education                                   691 non-null    int64  \n 33  Patents: AI use cases: Energy                                      691 non-null    int64  \n 34  Patents: AI use cases: Entertainment                               691 non-null    int64  \n 35  Patents: AI use cases: Industry and manufacturing                  691 non-null    int64  \n 36  Patents: AI use cases: Life sciences                               691 non-null    int64  \n 37  Patents: AI use cases: Military                                    691 non-null    int64  \n 38  Patents: AI use cases: Nanotechnology                              691 non-null    int64  \n 39  Patents: AI use cases: Networking                                  691 non-null    int64  \n 40  Patents: AI use cases: Personal devices and computing              691 non-null    int64  \n 41  Patents: AI use cases: Physical sciences and engineering           691 non-null    int64  \n 42  Patents: AI use cases: Security                                    691 non-null    int64  \n 43  Patents: AI use cases: Semiconductors                              691 non-null    int64  \n 44  Patents: AI use cases: Telecommunications                          691 non-null    int64  \n 45  Patents: AI use cases: Transportation                              691 non-null    int64  \n 46  Patents: AI applications and techniques: Analytics and algorithms  691 non-null    int64  \n 47  Patents: AI applications and techniques: Computer vision           691 non-null    int64  \n 48  Patents: AI applications and techniques: Control                   691 non-null    int64  \n 49  Patents: AI applications and techniques: Distributed AI            691 non-null    int64  \n 50  Patents: AI applications and techniques: Knowledge representation  691 non-null    int64  \n 51  Patents: AI applications and techniques: Language processing       691 non-null    int64  \n 52  Patents: AI applications and techniques: Measuring and testing     691 non-null    int64  \n 53  Patents: AI applications and techniques: Planning and scheduling   691 non-null    int64  \n 54  Patents: AI applications and techniques: Robotics                  691 non-null    int64  \n 55  Patents: AI applications and techniques: Speech processing         691 non-null    int64  \n 56  Workforce: AI workers                                              691 non-null    int64  \n 57  Workforce: Tech Team 1 workers                                     691 non-null    int64  \n 58  City                                                               690 non-null    object \n 59  State/province                                                     679 non-null    object \n 60  PARAT link                                                         691 non-null    object \ndtypes: float64(4), int64(42), object(15)\nmemory usage: 329.4+ KB\n```\n:::\n:::\n\n\n### Analysis plan\nSome data cleaning will need to take place to identify missing data and outliers. Some variables that may require significant decision making about the scope of the data used to answer the research question are `Publications: Recent AI publication growth` and `Patents: AI patents: recent growth`, which each only have 331 rows compared to the 691 for most other variables. The variables involved in answering the research question are the company name/ID, variables within the Publications and Patents categories. There are no plans to integrate any other data sources, but if necessary the other tables in the dataset may contain information of use. After the data cleaning, wrangling, and EDA prcoess the data can be visualized and numerical statistics can be computed to understand the relationships between publications/patents and sector. \n\n## Dataset 3: Bachelor's degrees by field of study\n\n### Introduction and data\n\nThe Digest of Education Statistics includes data summarized from surveys administered by the National Center for Education Statistics (NCES) (and other government agencies) and Annual Reports. This data was collected by surveys administered to postsecondary institutions participating in Title IV federal financial aid programs. The tables can be found [here](https://nces.ed.gov/programs/digest/d22/tables/dt22_322.10.asp)\n\n#### Description of contents\n\nThere are 6 datasets that will be loaded, providing a combination of data on bachelor’s degrees conferred by either field of study, state, sex, or race/ethnicity. The datasets provide data either from a range of time (\\~1970-2021) or only two years (2019/20-2020/21). Below is an outline of each table and its contents. \n\n-   Table 319.30. Bachelor's degrees conferred by postsecondary institutions, by field of study and state or jurisdiction: Academic year 2020-21 \n-   Table 322.10. Bachelor's degrees conferred by postsecondary institutions, by field of study: Selected academic years, 1970-71 through 2020-21 \n-   Table 322.20. Bachelor's degrees conferred by postsecondary institutions, by race/ethnicity and sex of student: Selected academic years, 1976-77 through 2020-21 \n-   Table 322.30. Bachelor's degrees conferred by postsecondary institutions, by race/ethnicity and field of study: Academic years 2019-20 and 2020-21 \n-   Table 322.40. Bachelor's degrees conferred to males by postsecondary institutions, by race/ethnicity and field of study: Academic years 2019-20 and 2020-21 \n-   Table 322.50. Bachelor's degrees conferred to females by postsecondary institutions, by race/ethnicity and field of study: Academic years 2019-20 and 2020-21\n\n#### Ethical Concerns\n\nBecause the data was collected from surveys, it is possible that there could be missing patterns from universities that did not participate. Otherwise, there are no other glaring ethical concerns with the data.\n\n### Research Question\n\n-   How do gender and racial/ethnic diversity levels compare between those in newer and fast growing majors and those in more well established and traditional majors?\n\n    -   The target audience are universities and colleges.\n\n-   This question is important because it examines diversity trends within academia. The shifts in representation in a field can highlight progress in educational inclusion and access. Furthermore, this question can inform policies or awarness to support diversity in fields lacking representation.\n\n-   We hypothesize that newer, fast-growing majors have higher levels of diversity than more traditional majors.\n\n-   The categorical variables are the field of study, gender, and race/ethnicity. The quantitative variables include the year, and counts for each respective field of study and year or demographic feature\n\n### Glimpse of data\n\n#### Table 319.30.\tBachelor's degrees conferred by postsecondary institutions, by field of study and state or jurisdiction: Academic year 2020-21\n\n::: {#97c26b14 .cell execution_count=9}\n``` {.python .cell-code}\ntabn319_30 = pd.read_excel(\"data/education/tabn319.30.xlsx\")\n```\n:::\n\n\n::: {#6053a21e .cell execution_count=10}\n``` {.python .cell-code}\ntabn319_30.head()\n```\n\n::: {.cell-output .cell-output-display execution_count=9}\n```{=html}\n<div>\n<style scoped>\n    .dataframe tbody tr th:only-of-type {\n        vertical-align: middle;\n    }\n\n    .dataframe tbody tr th {\n        vertical-align: top;\n    }\n\n    .dataframe thead th {\n        text-align: right;\n    }\n</style>\n<table border=\"1\" class=\"dataframe\">\n  <thead>\n    <tr style=\"text-align: right;\">\n      <th></th>\n      <th>Table 319.30. Bachelor's degrees conferred by postsecondary institutions, by field of study and state or jurisdiction: Academic year 2020-21</th>\n      <th>Unnamed: 1</th>\n      <th>Unnamed: 2</th>\n      <th>Unnamed: 3</th>\n      <th>Unnamed: 4</th>\n      <th>Unnamed: 5</th>\n      <th>Unnamed: 6</th>\n      <th>Unnamed: 7</th>\n      <th>Unnamed: 8</th>\n      <th>Unnamed: 9</th>\n      <th>Unnamed: 10</th>\n      <th>Unnamed: 11</th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>0</th>\n      <td>State or jurisdiction</td>\n      <td>Total</td>\n      <td>Humanities\\1\\</td>\n      <td>Psychology</td>\n      <td>Social sciences and history</td>\n      <td>Natural sciences and mathematics\\2\\</td>\n      <td>Computer and information sciences and support ...</td>\n      <td>Engineering\\3\\</td>\n      <td>Education</td>\n      <td>Business\\4\\</td>\n      <td>Health professions and related programs</td>\n      <td>Other fields\\5\\</td>\n    </tr>\n    <tr>\n      <th>1</th>\n      <td>1</td>\n      <td>2</td>\n      <td>3</td>\n      <td>4</td>\n      <td>5</td>\n      <td>6</td>\n      <td>7</td>\n      <td>8</td>\n      <td>9</td>\n      <td>10</td>\n      <td>11</td>\n      <td>12</td>\n    </tr>\n    <tr>\n      <th>2</th>\n      <td>United States</td>\n      <td>2066445</td>\n      <td>263894</td>\n      <td>126944</td>\n      <td>160827</td>\n      <td>187829</td>\n      <td>104874</td>\n      <td>145041</td>\n      <td>89398</td>\n      <td>391375</td>\n      <td>268018</td>\n      <td>328245</td>\n    </tr>\n    <tr>\n      <th>3</th>\n      <td>Alabama</td>\n      <td>34821</td>\n      <td>2785</td>\n      <td>1523</td>\n      <td>1593</td>\n      <td>2851</td>\n      <td>1195</td>\n      <td>3832</td>\n      <td>1813</td>\n      <td>8272</td>\n      <td>4513</td>\n      <td>6444</td>\n    </tr>\n    <tr>\n      <th>4</th>\n      <td>Alaska</td>\n      <td>1812</td>\n      <td>273</td>\n      <td>110</td>\n      <td>124</td>\n      <td>159</td>\n      <td>29</td>\n      <td>166</td>\n      <td>57</td>\n      <td>320</td>\n      <td>261</td>\n      <td>313</td>\n    </tr>\n  </tbody>\n</table>\n</div>\n```\n:::\n:::\n\n\n#### Table 322.10. Bachelor's degrees conferred by postsecondary institutions, by field of study: Selected academic years, 1970-71 through 2020-21\n\n::: {#0ca33bc9 .cell execution_count=11}\n``` {.python .cell-code}\ntabn322_10 = pd.read_excel(\"data/education/tabn322.10.xlsx\")\n```\n:::\n\n\n::: {#53e665f0 .cell execution_count=12}\n``` {.python .cell-code}\ntabn322_10.head()\n```\n\n::: {.cell-output .cell-output-display execution_count=11}\n```{=html}\n<div>\n<style scoped>\n    .dataframe tbody tr th:only-of-type {\n        vertical-align: middle;\n    }\n\n    .dataframe tbody tr th {\n        vertical-align: top;\n    }\n\n    .dataframe thead th {\n        text-align: right;\n    }\n</style>\n<table border=\"1\" class=\"dataframe\">\n  <thead>\n    <tr style=\"text-align: right;\">\n      <th></th>\n      <th>Table 322.10. Bachelor's degrees conferred by postsecondary institutions, by field of study: Selected academic years, 1970-71 through 2020-21</th>\n      <th>Unnamed: 1</th>\n      <th>Unnamed: 2</th>\n      <th>Unnamed: 3</th>\n      <th>Unnamed: 4</th>\n      <th>Unnamed: 5</th>\n      <th>Unnamed: 6</th>\n      <th>Unnamed: 7</th>\n      <th>Unnamed: 8</th>\n      <th>Unnamed: 9</th>\n      <th>Unnamed: 10</th>\n      <th>Unnamed: 11</th>\n      <th>Unnamed: 12</th>\n      <th>Unnamed: 13</th>\n      <th>Unnamed: 14</th>\n      <th>Unnamed: 15</th>\n      <th>Unnamed: 16</th>\n      <th>Unnamed: 17</th>\n      <th>Unnamed: 18</th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>0</th>\n      <td>Field of study</td>\n      <td>1970-71</td>\n      <td>1975-76</td>\n      <td>1980-81</td>\n      <td>1985-86</td>\n      <td>1990-91</td>\n      <td>1995-96</td>\n      <td>2000-01</td>\n      <td>2005-06</td>\n      <td>2011-12</td>\n      <td>2012-13</td>\n      <td>2013-14</td>\n      <td>2014-15</td>\n      <td>2015-16</td>\n      <td>2016-17</td>\n      <td>2017-18</td>\n      <td>2018-19</td>\n      <td>2019-20</td>\n      <td>2020-21</td>\n    </tr>\n    <tr>\n      <th>1</th>\n      <td>1</td>\n      <td>2</td>\n      <td>3</td>\n      <td>4</td>\n      <td>5</td>\n      <td>6</td>\n      <td>7</td>\n      <td>8</td>\n      <td>9</td>\n      <td>10</td>\n      <td>11</td>\n      <td>12</td>\n      <td>13</td>\n      <td>14</td>\n      <td>15</td>\n      <td>16</td>\n      <td>17</td>\n      <td>18</td>\n      <td>19</td>\n    </tr>\n    <tr>\n      <th>2</th>\n      <td>Total</td>\n      <td>839730</td>\n      <td>925746</td>\n      <td>935140</td>\n      <td>987823</td>\n      <td>1094538</td>\n      <td>1164792</td>\n      <td>1244171</td>\n      <td>1485104</td>\n      <td>1792163</td>\n      <td>1840381</td>\n      <td>1870150</td>\n      <td>1894969</td>\n      <td>1920750</td>\n      <td>1956114</td>\n      <td>1980665</td>\n      <td>2013086</td>\n      <td>2038682</td>\n      <td>2066445</td>\n    </tr>\n    <tr>\n      <th>3</th>\n      <td>Agriculture and natural resources\\1\\</td>\n      <td>12674</td>\n      <td>19402</td>\n      <td>21886</td>\n      <td>17191</td>\n      <td>13363</td>\n      <td>21757</td>\n      <td>23766</td>\n      <td>23497</td>\n      <td>31629</td>\n      <td>34304</td>\n      <td>35953</td>\n      <td>37028</td>\n      <td>37827</td>\n      <td>38782</td>\n      <td>40334</td>\n      <td>41373</td>\n      <td>41858</td>\n      <td>41925</td>\n    </tr>\n    <tr>\n      <th>4</th>\n      <td>Architecture and related services</td>\n      <td>5570</td>\n      <td>9146</td>\n      <td>9455</td>\n      <td>9119</td>\n      <td>9781</td>\n      <td>8352</td>\n      <td>8480</td>\n      <td>9515</td>\n      <td>9727</td>\n      <td>9757</td>\n      <td>9149</td>\n      <td>9090</td>\n      <td>8825</td>\n      <td>8579</td>\n      <td>8464</td>\n      <td>8806</td>\n      <td>9045</td>\n      <td>9296</td>\n    </tr>\n  </tbody>\n</table>\n</div>\n```\n:::\n:::\n\n\n#### Table 322.20. Bachelor's degrees conferred by postsecondary institutions, by race/ethnicity and sex of student: Selected academic years, 1976-77 through 2020-21\n\n::: {#02b881c6 .cell execution_count=13}\n``` {.python .cell-code}\ntabn322_20 = pd.read_excel(\"data/education/tabn322.20.xlsx\")\n```\n:::\n\n\n::: {#9b06b452 .cell execution_count=14}\n``` {.python .cell-code}\ntabn322_20.head()\n```\n\n::: {.cell-output .cell-output-display execution_count=13}\n```{=html}\n<div>\n<style scoped>\n    .dataframe tbody tr th:only-of-type {\n        vertical-align: middle;\n    }\n\n    .dataframe tbody tr th {\n        vertical-align: top;\n    }\n\n    .dataframe thead th {\n        text-align: right;\n    }\n</style>\n<table border=\"1\" class=\"dataframe\">\n  <thead>\n    <tr style=\"text-align: right;\">\n      <th></th>\n      <th>Table 322.20. Bachelor's degrees conferred by postsecondary institutions, by race/ethnicity and sex of student: Selected academic years, 1976-77 through 2020-21</th>\n      <th>Unnamed: 1</th>\n      <th>Unnamed: 2</th>\n      <th>Unnamed: 3</th>\n      <th>Unnamed: 4</th>\n      <th>Unnamed: 5</th>\n      <th>Unnamed: 6</th>\n      <th>Unnamed: 7</th>\n      <th>Unnamed: 8</th>\n      <th>Unnamed: 9</th>\n      <th>Unnamed: 10</th>\n      <th>Unnamed: 11</th>\n      <th>Unnamed: 12</th>\n      <th>Unnamed: 13</th>\n      <th>Unnamed: 14</th>\n      <th>Unnamed: 15</th>\n      <th>Unnamed: 16</th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>0</th>\n      <td>Year and sex</td>\n      <td>Number of degrees conferred to U.S. citizens, ...</td>\n      <td>Number of degrees conferred to U.S. citizens, ...</td>\n      <td>Number of degrees conferred to U.S. citizens, ...</td>\n      <td>Number of degrees conferred to U.S. citizens, ...</td>\n      <td>Number of degrees conferred to U.S. citizens, ...</td>\n      <td>Number of degrees conferred to U.S. citizens, ...</td>\n      <td>Number of degrees conferred to U.S. citizens, ...</td>\n      <td>Number of degrees conferred to U.S. citizens, ...</td>\n      <td>Number of degrees conferred to U.S. citizens, ...</td>\n      <td>Percentage distribution of degrees conferred t...</td>\n      <td>Percentage distribution of degrees conferred t...</td>\n      <td>Percentage distribution of degrees conferred t...</td>\n      <td>Percentage distribution of degrees conferred t...</td>\n      <td>Percentage distribution of degrees conferred t...</td>\n      <td>Percentage distribution of degrees conferred t...</td>\n      <td>Percentage distribution of degrees conferred t...</td>\n    </tr>\n    <tr>\n      <th>1</th>\n      <td>Year and sex</td>\n      <td>Total</td>\n      <td>Total</td>\n      <td>White</td>\n      <td>Black</td>\n      <td>Hispanic</td>\n      <td>Asian/Pacific Islander</td>\n      <td>American Indian/Alaska Native</td>\n      <td>Two or more races\\1\\</td>\n      <td>Nonresident</td>\n      <td>Total</td>\n      <td>White</td>\n      <td>Black</td>\n      <td>Hispanic</td>\n      <td>Asian/Pacific Islander</td>\n      <td>American Indian/Alaska Native</td>\n      <td>Two or more races\\1\\</td>\n    </tr>\n    <tr>\n      <th>2</th>\n      <td>1</td>\n      <td>2</td>\n      <td>2</td>\n      <td>3</td>\n      <td>4</td>\n      <td>5</td>\n      <td>6</td>\n      <td>7</td>\n      <td>8</td>\n      <td>9</td>\n      <td>10</td>\n      <td>11</td>\n      <td>12</td>\n      <td>13</td>\n      <td>14</td>\n      <td>15</td>\n      <td>16</td>\n    </tr>\n    <tr>\n      <th>3</th>\n      <td>Total</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>NaN</td>\n    </tr>\n    <tr>\n      <th>4</th>\n      <td>1976-77</td>\n      <td>919549</td>\n      <td>\\2,3\\</td>\n      <td>807688</td>\n      <td>58636</td>\n      <td>18743</td>\n      <td>13793</td>\n      <td>3326</td>\n      <td>---</td>\n      <td>15714</td>\n      <td>100</td>\n      <td>89.525663</td>\n      <td>6.499325</td>\n      <td>2.07751</td>\n      <td>1.528842</td>\n      <td>0.36866</td>\n      <td>---</td>\n    </tr>\n  </tbody>\n</table>\n</div>\n```\n:::\n:::\n\n\n#### Table 322.30.\tBachelor's degrees conferred by postsecondary institutions, by race/ethnicity and field of study: Academic years 2019-20 and 2020-21\n\n::: {#187f9aa5 .cell execution_count=15}\n``` {.python .cell-code}\ntabn322_30 = pd.read_excel(\"data/education/tabn322.30.xlsx\")\n```\n:::\n\n\n::: {#416e5d73 .cell execution_count=16}\n``` {.python .cell-code}\ntabn322_30.head()\n```\n\n::: {.cell-output .cell-output-display execution_count=15}\n```{=html}\n<div>\n<style scoped>\n    .dataframe tbody tr th:only-of-type {\n        vertical-align: middle;\n    }\n\n    .dataframe tbody tr th {\n        vertical-align: top;\n    }\n\n    .dataframe thead th {\n        text-align: right;\n    }\n</style>\n<table border=\"1\" class=\"dataframe\">\n  <thead>\n    <tr style=\"text-align: right;\">\n      <th></th>\n      <th>Table 322.30. Bachelor's degrees conferred by postsecondary institutions, by race/ethnicity and field of study: Academic years 2019-20 and 2020-21</th>\n      <th>Unnamed: 1</th>\n      <th>Unnamed: 2</th>\n      <th>Unnamed: 3</th>\n      <th>Unnamed: 4</th>\n      <th>Unnamed: 5</th>\n      <th>Unnamed: 6</th>\n      <th>Unnamed: 7</th>\n      <th>Unnamed: 8</th>\n      <th>Unnamed: 9</th>\n      <th>...</th>\n      <th>Unnamed: 11</th>\n      <th>Unnamed: 12</th>\n      <th>Unnamed: 13</th>\n      <th>Unnamed: 14</th>\n      <th>Unnamed: 15</th>\n      <th>Unnamed: 16</th>\n      <th>Unnamed: 17</th>\n      <th>Unnamed: 18</th>\n      <th>Unnamed: 19</th>\n      <th>Unnamed: 20</th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>0</th>\n      <td>Field of study</td>\n      <td>2019-20</td>\n      <td>2019-20</td>\n      <td>2019-20</td>\n      <td>2019-20</td>\n      <td>2019-20</td>\n      <td>2019-20</td>\n      <td>2019-20</td>\n      <td>2019-20</td>\n      <td>2019-20</td>\n      <td>...</td>\n      <td>2020-21</td>\n      <td>2020-21</td>\n      <td>2020-21</td>\n      <td>2020-21</td>\n      <td>2020-21</td>\n      <td>2020-21</td>\n      <td>2020-21</td>\n      <td>2020-21</td>\n      <td>2020-21</td>\n      <td>2020-21</td>\n    </tr>\n    <tr>\n      <th>1</th>\n      <td>Field of study</td>\n      <td>Total</td>\n      <td>White</td>\n      <td>Black</td>\n      <td>Hispanic</td>\n      <td>Asian/Pacific Islander</td>\n      <td>Asian/Pacific Islander</td>\n      <td>Asian/Pacific Islander</td>\n      <td>American Indian/Alaska Native</td>\n      <td>Two or more races</td>\n      <td>...</td>\n      <td>Total</td>\n      <td>White</td>\n      <td>Black</td>\n      <td>Hispanic</td>\n      <td>Asian/Pacific Islander</td>\n      <td>Asian/Pacific Islander</td>\n      <td>Asian/Pacific Islander</td>\n      <td>American Indian/Alaska Native</td>\n      <td>Two or more races</td>\n      <td>Nonresident</td>\n    </tr>\n    <tr>\n      <th>2</th>\n      <td>Field of study</td>\n      <td>Total</td>\n      <td>White</td>\n      <td>Black</td>\n      <td>Hispanic</td>\n      <td>Total</td>\n      <td>Asian</td>\n      <td>Pacific Islander</td>\n      <td>American Indian/Alaska Native</td>\n      <td>Two or more races</td>\n      <td>...</td>\n      <td>Total</td>\n      <td>White</td>\n      <td>Black</td>\n      <td>Hispanic</td>\n      <td>Total</td>\n      <td>Asian</td>\n      <td>Pacific Islander</td>\n      <td>American Indian/Alaska Native</td>\n      <td>Two or more races</td>\n      <td>Nonresident</td>\n    </tr>\n    <tr>\n      <th>3</th>\n      <td>1</td>\n      <td>2</td>\n      <td>3</td>\n      <td>4</td>\n      <td>5</td>\n      <td>6</td>\n      <td>7</td>\n      <td>8</td>\n      <td>9</td>\n      <td>10</td>\n      <td>...</td>\n      <td>12</td>\n      <td>13</td>\n      <td>14</td>\n      <td>15</td>\n      <td>16</td>\n      <td>17</td>\n      <td>18</td>\n      <td>19</td>\n      <td>20</td>\n      <td>21</td>\n    </tr>\n    <tr>\n      <th>4</th>\n      <td>All fields, total</td>\n      <td>2038682</td>\n      <td>1184082</td>\n      <td>197491</td>\n      <td>302663</td>\n      <td>161468</td>\n      <td>157085</td>\n      <td>4383</td>\n      <td>9154</td>\n      <td>77621</td>\n      <td>...</td>\n      <td>2066445</td>\n      <td>1172187</td>\n      <td>206527</td>\n      <td>324848</td>\n      <td>169261</td>\n      <td>164845</td>\n      <td>4416</td>\n      <td>9545</td>\n      <td>81369</td>\n      <td>102708</td>\n    </tr>\n  </tbody>\n</table>\n<p>5 rows × 21 columns</p>\n</div>\n```\n:::\n:::\n\n\n#### Table 322.40.\tBachelor's degrees conferred to males by postsecondary institutions, by race/ethnicity and field of study: Academic years 2019-20 and 2020-21\n\n::: {#f037fa94 .cell execution_count=17}\n``` {.python .cell-code}\ntabn322_40 = pd.read_excel(\"data/education/tabn322.40.xlsx\")\n```\n:::\n\n\n::: {#76174e82 .cell execution_count=18}\n``` {.python .cell-code}\ntabn322_40.head()\n```\n\n::: {.cell-output .cell-output-display execution_count=17}\n```{=html}\n<div>\n<style scoped>\n    .dataframe tbody tr th:only-of-type {\n        vertical-align: middle;\n    }\n\n    .dataframe tbody tr th {\n        vertical-align: top;\n    }\n\n    .dataframe thead th {\n        text-align: right;\n    }\n</style>\n<table border=\"1\" class=\"dataframe\">\n  <thead>\n    <tr style=\"text-align: right;\">\n      <th></th>\n      <th>Table 322.40. Bachelor's degrees conferred to males by postsecondary institutions, by race/ethnicity and field of study: Academic years 2019-20 and 2020-21</th>\n      <th>Unnamed: 1</th>\n      <th>Unnamed: 2</th>\n      <th>Unnamed: 3</th>\n      <th>Unnamed: 4</th>\n      <th>Unnamed: 5</th>\n      <th>Unnamed: 6</th>\n      <th>Unnamed: 7</th>\n      <th>Unnamed: 8</th>\n      <th>Unnamed: 9</th>\n      <th>...</th>\n      <th>Unnamed: 11</th>\n      <th>Unnamed: 12</th>\n      <th>Unnamed: 13</th>\n      <th>Unnamed: 14</th>\n      <th>Unnamed: 15</th>\n      <th>Unnamed: 16</th>\n      <th>Unnamed: 17</th>\n      <th>Unnamed: 18</th>\n      <th>Unnamed: 19</th>\n      <th>Unnamed: 20</th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>0</th>\n      <td>Field of study</td>\n      <td>2019-20</td>\n      <td>2019-20</td>\n      <td>2019-20</td>\n      <td>2019-20</td>\n      <td>2019-20</td>\n      <td>2019-20</td>\n      <td>2019-20</td>\n      <td>2019-20</td>\n      <td>2019-20</td>\n      <td>...</td>\n      <td>2020-21</td>\n      <td>2020-21</td>\n      <td>2020-21</td>\n      <td>2020-21</td>\n      <td>2020-21</td>\n      <td>2020-21</td>\n      <td>2020-21</td>\n      <td>2020-21</td>\n      <td>2020-21</td>\n      <td>2020-21</td>\n    </tr>\n    <tr>\n      <th>1</th>\n      <td>Field of study</td>\n      <td>Total</td>\n      <td>White</td>\n      <td>Black</td>\n      <td>Hispanic</td>\n      <td>Asian/Pacific Islander</td>\n      <td>Asian/Pacific Islander</td>\n      <td>Asian/Pacific Islander</td>\n      <td>American Indian/Alaska Native</td>\n      <td>Two or more races</td>\n      <td>...</td>\n      <td>Total</td>\n      <td>White</td>\n      <td>Black</td>\n      <td>Hispanic</td>\n      <td>Asian/Pacific Islander</td>\n      <td>Asian/Pacific Islander</td>\n      <td>Asian/Pacific Islander</td>\n      <td>American Indian/Alaska Native</td>\n      <td>Two or more races</td>\n      <td>Nonresident</td>\n    </tr>\n    <tr>\n      <th>2</th>\n      <td>Field of study</td>\n      <td>Total</td>\n      <td>White</td>\n      <td>Black</td>\n      <td>Hispanic</td>\n      <td>Total</td>\n      <td>Asian</td>\n      <td>Pacific Islander</td>\n      <td>American Indian/Alaska Native</td>\n      <td>Two or more races</td>\n      <td>...</td>\n      <td>Total</td>\n      <td>White</td>\n      <td>Black</td>\n      <td>Hispanic</td>\n      <td>Total</td>\n      <td>Asian</td>\n      <td>Pacific Islander</td>\n      <td>American Indian/Alaska Native</td>\n      <td>Two or more races</td>\n      <td>Nonresident</td>\n    </tr>\n    <tr>\n      <th>3</th>\n      <td>1</td>\n      <td>2</td>\n      <td>3</td>\n      <td>4</td>\n      <td>5</td>\n      <td>6</td>\n      <td>7</td>\n      <td>8</td>\n      <td>9</td>\n      <td>10</td>\n      <td>...</td>\n      <td>12</td>\n      <td>13</td>\n      <td>14</td>\n      <td>15</td>\n      <td>16</td>\n      <td>17</td>\n      <td>18</td>\n      <td>19</td>\n      <td>20</td>\n      <td>21</td>\n    </tr>\n    <tr>\n      <th>4</th>\n      <td>All fields, total</td>\n      <td>861384</td>\n      <td>509079</td>\n      <td>70346</td>\n      <td>117230</td>\n      <td>72916</td>\n      <td>71005</td>\n      <td>1911</td>\n      <td>3344</td>\n      <td>31620</td>\n      <td>...</td>\n      <td>860764</td>\n      <td>499092</td>\n      <td>72092</td>\n      <td>123256</td>\n      <td>75704</td>\n      <td>73835</td>\n      <td>1869</td>\n      <td>3407</td>\n      <td>33003</td>\n      <td>54210</td>\n    </tr>\n  </tbody>\n</table>\n<p>5 rows × 21 columns</p>\n</div>\n```\n:::\n:::\n\n\n#### Table 322.50.\tBachelor's degrees conferred to females by postsecondary institutions, by race/ethnicity and field of study: Academic years 2019-20 and 2020-21\n\n::: {#1952d1b6 .cell execution_count=19}\n``` {.python .cell-code}\ntabn322_50 = pd.read_excel(\"data/education/tabn322.50.xlsx\")\n```\n:::\n\n\n::: {#e4907572 .cell execution_count=20}\n``` {.python .cell-code}\ntabn322_50.head()\n```\n\n::: {.cell-output .cell-output-display execution_count=19}\n```{=html}\n<div>\n<style scoped>\n    .dataframe tbody tr th:only-of-type {\n        vertical-align: middle;\n    }\n\n    .dataframe tbody tr th {\n        vertical-align: top;\n    }\n\n    .dataframe thead th {\n        text-align: right;\n    }\n</style>\n<table border=\"1\" class=\"dataframe\">\n  <thead>\n    <tr style=\"text-align: right;\">\n      <th></th>\n      <th>Table 322.50. Bachelor's degrees conferred to females by postsecondary institutions, by race/ethnicity and field of study: Academic years 2019-20 and 2020-21</th>\n      <th>Unnamed: 1</th>\n      <th>Unnamed: 2</th>\n      <th>Unnamed: 3</th>\n      <th>Unnamed: 4</th>\n      <th>Unnamed: 5</th>\n      <th>Unnamed: 6</th>\n      <th>Unnamed: 7</th>\n      <th>Unnamed: 8</th>\n      <th>Unnamed: 9</th>\n      <th>...</th>\n      <th>Unnamed: 11</th>\n      <th>Unnamed: 12</th>\n      <th>Unnamed: 13</th>\n      <th>Unnamed: 14</th>\n      <th>Unnamed: 15</th>\n      <th>Unnamed: 16</th>\n      <th>Unnamed: 17</th>\n      <th>Unnamed: 18</th>\n      <th>Unnamed: 19</th>\n      <th>Unnamed: 20</th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>0</th>\n      <td>Field of study</td>\n      <td>2019-20</td>\n      <td>2019-20</td>\n      <td>2019-20</td>\n      <td>2019-20</td>\n      <td>2019-20</td>\n      <td>2019-20</td>\n      <td>2019-20</td>\n      <td>2019-20</td>\n      <td>2019-20</td>\n      <td>...</td>\n      <td>2020-21</td>\n      <td>2020-21</td>\n      <td>2020-21</td>\n      <td>2020-21</td>\n      <td>2020-21</td>\n      <td>2020-21</td>\n      <td>2020-21</td>\n      <td>2020-21</td>\n      <td>2020-21</td>\n      <td>2020-21</td>\n    </tr>\n    <tr>\n      <th>1</th>\n      <td>Field of study</td>\n      <td>Total</td>\n      <td>White</td>\n      <td>Black</td>\n      <td>Hispanic</td>\n      <td>Asian/Pacific Islander</td>\n      <td>Asian/Pacific Islander</td>\n      <td>Asian/Pacific Islander</td>\n      <td>American Indian/Alaska Native</td>\n      <td>Two or more races</td>\n      <td>...</td>\n      <td>Total</td>\n      <td>White</td>\n      <td>Black</td>\n      <td>Hispanic</td>\n      <td>Asian/Pacific Islander</td>\n      <td>Asian/Pacific Islander</td>\n      <td>Asian/Pacific Islander</td>\n      <td>American Indian/Alaska Native</td>\n      <td>Two or more races</td>\n      <td>Nonresident</td>\n    </tr>\n    <tr>\n      <th>2</th>\n      <td>Field of study</td>\n      <td>Total</td>\n      <td>White</td>\n      <td>Black</td>\n      <td>Hispanic</td>\n      <td>Total</td>\n      <td>Asian</td>\n      <td>Pacific Islander</td>\n      <td>American Indian/Alaska Native</td>\n      <td>Two or more races</td>\n      <td>...</td>\n      <td>Total</td>\n      <td>White</td>\n      <td>Black</td>\n      <td>Hispanic</td>\n      <td>Total</td>\n      <td>Asian</td>\n      <td>Pacific Islander</td>\n      <td>American Indian/Alaska Native</td>\n      <td>Two or more races</td>\n      <td>Nonresident</td>\n    </tr>\n    <tr>\n      <th>3</th>\n      <td>1</td>\n      <td>2</td>\n      <td>3</td>\n      <td>4</td>\n      <td>5</td>\n      <td>6</td>\n      <td>7</td>\n      <td>8</td>\n      <td>9</td>\n      <td>10</td>\n      <td>...</td>\n      <td>12</td>\n      <td>13</td>\n      <td>14</td>\n      <td>15</td>\n      <td>16</td>\n      <td>17</td>\n      <td>18</td>\n      <td>19</td>\n      <td>20</td>\n      <td>21</td>\n    </tr>\n    <tr>\n      <th>4</th>\n      <td>All fields, total</td>\n      <td>1177298</td>\n      <td>675003</td>\n      <td>127145</td>\n      <td>185433</td>\n      <td>88552</td>\n      <td>86080</td>\n      <td>2472</td>\n      <td>5810</td>\n      <td>46001</td>\n      <td>...</td>\n      <td>1205681</td>\n      <td>673095</td>\n      <td>134435</td>\n      <td>201592</td>\n      <td>93557</td>\n      <td>91010</td>\n      <td>2547</td>\n      <td>6138</td>\n      <td>48366</td>\n      <td>48498</td>\n    </tr>\n  </tbody>\n</table>\n<p>5 rows × 21 columns</p>\n</div>\n```\n:::\n:::\n\n\n### Analysis plan\n\nThe tables will need to be integrated into a tabular format containing the information needed to answer the research question. There is little to no missing data and the individual tables are already highly structured but there will likely be significant wrangling needed to integrate the tables into a usable format. After the tables are integrated, summary statistics can be calculated and the data can be visualized to answer the research question.\n\nOnce the tables are in a usable format, there are two questions that will need to be answered. First, we will need to identify what majors are traditional and which would be considered fast-growing. That is, which majors have historically and continue to be conferred highly, compared to those that only recently have begun to increase in numbers. From here, then we will investigate the demographic makeup of graduates for different fields of study. Because there are a significant number of majors listed, only a select few majors of interest (i.e. the most traditional and most new majors) will be looked at.\n\n",
    "supporting": [
      "proposal_files/figure-html"
    ],
    "filters": [],
    "includes": {
      "include-in-header": [
        "<script src=\"https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.6/require.min.js\" integrity=\"sha512-c3Nl8+7g4LMSTdrm621y7kf9v3SDPnhxLNhcjFJbKECVnmZHTdo+IRO05sNLTH/D3vA6u1X32ehoLC7WFVdheg==\" crossorigin=\"anonymous\"></script>\n<script src=\"https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js\" integrity=\"sha512-bLT0Qm9VnAYZDflyKcBaQ2gg0hSYNQrJ8RilYldYQ1FxQYoCLtUjuuRuZo+fjqhx/qtq/1itJ0C2ejDxltZVFg==\" crossorigin=\"anonymous\" data-relocate-top=\"true\"></script>\n<script type=\"application/javascript\">define('jquery', [],function() {return window.jQuery;})</script>\n"
      ]
    }
  }
}